name: super_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  routemaster: ^1.0.1
  cupertino_icons: ^1.0.8
  fav_qs_api:
    path: packages/fav_qs_api
  quote_repository:
    path: packages/quote_repository
  user_repository:
    path: packages/user_repository
  quote_list:
    path: packages/features/quote_list
  sign_in:
    path: packages/features/sign_in
  domain_models:
    path: packages/domain_models
  component_library:
    path: packages/component_library
  key_value_storage:
    path: packages/key_value_storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true