# Uncomment the next line to define a global platform for your project
platform :ios, '18.0'

flutter_application_path = '../../modules/f_home'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')


target 'FNative' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  install_all_flutter_pods(flutter_application_path)


  # Pods for FNative

  target 'FNativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FNativeUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end
